import { Metadata } from "next";
import "./globals.css";
// import { SpeedInsights } from "@vercel/speed-insights/next";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { PointsProvider } from "@/context/PointsContext";
import { SpeedInsights } from "@vercel/speed-insights/next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <PointsProvider>
          <Header />
          <main className="min-h-screen">{children}</main>
          <SpeedInsights />
          <Footer />
        </PointsProvider>
      </body>
    </html>
  );
}
